---
- name: Configure Ubuntu
  become: yes
  hosts: all
  become_method: sudo
  remote_user: ubuntu

  tasks:
    - name: update packages
      apt:
        update_cache: yes

    - name: upgrade packages
      apt: 
        name: "*"
        state: latest

    - import_tasks: ../SPEDI-Tasks/network.yml

    